#cloud-config
packages:
  - httpd
  - mariadb-server
  - mariadb
  - php
  - php-mysql
  - php-gd
  - php-mcrypt
write_files:
  - path: /var/www/html/info.php
    content: |
      <?php
      phpinfo();
      ?>
runcmd:
  - 'chown apache:apache /var/www/html/info.php'
  - systemctl start httpd.service && systemctl enable httpd.service
  - systemctl start mariadb && systemctl enable mariadb.service
